services:
#  prometheus:
#    image: prom/prometheus:latest
#    container_name: prometheus
#    restart: unless-stopped
#    command:
#      - --config.file=/etc/prometheus/prometheus.yml
#      - --storage.tsdb.path=/prometheus
#      - --web.enable-lifecycle
#    volumes:
#      - ./config/prometheus.yaml:/etc/prometheus/prometheus.yml:ro
#    ports:
#      - "9090"
  hardware_exporter:
    image: ghcr.io/danielr1996/hardware_exporter
    container_name: hardware_exporter
    ports:
      - "9105:9105"