scrape_configs:
  - job_name: 'inventory'
    dns_sd_configs:
      - names:
          - '_tcp._inventory.danielr1996.de'
        type: SRV
        refresh_interval: 30s
    relabel_configs:
      - source_labels: [__address__]
        regex: '([^:]+):([0-9]+)'
        replacement: 'http://$1:$2/metrics'
        target_label: instance